export default {
    CHANNEL_MESSAGE_RECEIVED: "CHANNEL_MESSAGE_RECEIVED",
    PRIVATE_MESSAGE_RECEIVED: "PRIVATE_MESSAGE_RECEIVED",
    INIT_CHANNEL_MESSAGES_MAP: "INIT_CHANNEL_MESSAGES_MAP",
    INIT_PRIVATE_MESSAGES_MAP: "INIT_PRIVATE_MESSAGES_MAP",
    INIT_CHANNEL_MESSAGES: "INIT_CHANNEL_MESSAGES",
    SET_CHANNEL_MESSAGES: "SET_CHANNEL_MESSAGES",
    SET_PRIVATE_MESSAGES: "SET_PRIVATE_MESSAGES",
};