export default {
    CHANNEL_MESSAGE_RECEIVED: "CHANNEL_MESSAGE_RECEIVED",
    PRIVATE_MESSAGE_RECEIVED: "PRIVATE_MESSAGE_RECEIVED",
    SET_CHANNEL_MESSAGES: "SET_CHANNEL_MESSAGES",
    SET_PRIVATE_MESSAGES: "SET_PRIVATE_MESSAGES",
};