export default {
    SHOW_INVITE_MODAL: 'SHOW_INVITE_MODAL',
    FETCH_INVITATIONS: 'FETCH_INVITATIONS',
    SHOW_INVITATIONS_MODAL: 'SHOW_INVITATIONS_MODAL',
    SET_INVITED_USER_EMAIL: 'SET_INVITED_USER_EMAIL',
    UPDATE_INVITATIONS: 'UPDATE_INVITATIONS',
}