export default {
    SHOW_INVITE_MEMBERS_MODAL: 'SHOW_INVITE_MEMBERS_MODAL',
    FETCH_INVITATIONS: 'FETCH_INVITATIONS',
    SHOW_PENDING_INVITATIONS_MODAL: 'SHOW_PENDING_INVITATIONS_MODAL',
    REMOVE_INVITATION: 'REMOVE_INVITATION',
}