export default {
    FETCH_ORGS: 'FETCH_ORGS',
    SHOW_CREATE_ORG_MODAL: 'SHOW_CREATE_ORG_MODAL',
    SET_CREATE_ORG_NAME: 'SET_CREATE_ORG_NAME',
    ORG_NAME_TAKEN: 'ORG_NAME_TAKEN',
    SET_NEW_ORG_USERS: 'SET_NEW_ORG_USERS',
    SELECT_ORG: 'SELECT_ORG',
}