export default {
    SET_ORGS: 'SET_ORGS',
    SET_ORG: 'SET_ORG',
    ADD_ORG_MEMBER: 'ADD_ORG_MEMBER',
    SET_ORG_MEMBER_ONLINE_STATUS: 'SET_ORG_MEMBER_ONLINE_STATUS',
    SHOW_CREATE_ORG_MODAL: 'SHOW_CREATE_ORG_MODAL',
    SET_CREATE_ORG_NAME: 'SET_CREATE_ORG_NAME',
    ORG_NAME_TAKEN: 'ORG_NAME_TAKEN',
    SET_NEW_ORG_USERS: 'SET_NEW_ORG_USERS',
    SELECT_ORG: 'SELECT_ORG',
}