export default {
    SET_ORGS: 'SET_ORGS',
    SET_ORG: 'SET_ORG',
    ADD_ORG_MEMBER: 'ADD_ORG_MEMBER',
    SET_ORG_MEMBER_ONLINE_STATUS: 'SET_ORG_MEMBER_ONLINE_STATUS',
    SHOW_CREATE_ORG_MODAL: 'SHOW_CREATE_ORG_MODAL',
    SET_CURRENT_ORG: 'SET_CURRENT_ORG',
    SHOW_ORG_SETTINGS_MODAL: 'SHOW_ORG_SETTINGS_MODAL',
}