// Credit: https://github.com/dprovodnikov/complex-redux-project-architecture

export default {
	SET_ORG_CHANNELS: "SET_ORG_CHANNELS",
	ADDED_TO_CHANNEL: "ADDED_TO_CHANNEL",
	SHOW_CREATE_CHANNEL_MODAL: "SHOW_CREATE_CHANNEL_MODAL",
	ADD_MEMBERS_TO_CHANNEL: "ADD_MEMBERS_TO_CHANNEL",

	SET_CHANNEL_MEMBERS: "SET_CHANNEL_MEMBERS",
	SHOW_CHANNEL_SIDE_BAR: "SHOW_CHANNEL_SIDE_BAR",
	FETCH_CHANNEL_MEMBER_NAMES: "FETCH_CHANNEL_MEMBER_NAMES",
	REMOVE_CHANNEL_MEMBER: "REMOVE_CHANNEL_MEMBER",
};


 
