// Credit: https://github.com/dprovodnikov/complex-redux-project-architecture

export default {
    CHANNEL_NAME_TAKEN: 'CHANNEL_NAME_TAKEN',
    CHANNEL_NAME_SET: 'CHANNEL_NAME_SET',
    SHOW_CREATE_MODAL: 'SHOW_CREATE_MODAL',
    CREATE_PRIVATE:' CREATE_PRIVATE',
    PRIVATE_CHANNEL_USERS: 'PRIVATE_CHANNEL_USERS',
    ADDED_TO_CHANNEL: 'ADDED_TO_CHANNEL',
    SET_ORG_CHANNELS: 'SET_ORG_CHANNELS',
}
