export default {
    SET_USERNAME: "SET_USERNAME",
    TAKEN_USERNAME:"TAKEN_USERNAME", 
    FETCH_USERNAMES: "FETCH_USERNAMES",
    FORM_FIELD_UPDATED: "FORM_FIELD_UPDATED",
    RESET_FORM: "RESET_FORM",
};







