export default {
    SET_USERNAME: "SET_USERNAME",
    TAKEN_USERNAME:"TAKEN_USERNAME", 
    FETCH_USERNAMES: "FETCH_USERNAMES",
    WRONG_USERNAME: "WRONG_USERNAME",
    WRONG_PASSWORD: "WRONG_PASSWORD",
    SET_PASSWORD: "SET_PASSWORD",
};







