export default {
    SET_USERNAME: "SET_USERNAME",
    TAKEN_USERNAME:"TAKEN_USERNAME", 
    FETCH_USERNAMES: "FETCH_USERNAMES",
    SET_PASSWORD: "SET_PASSWORD",
    MISSING_CREDENTIALS: "MISSING_CREDENTIALS",
    INCORRECT_CREDENTIALS: "INCORRECT_CREDENTIALS",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
};







